version: "3.7"

services:
  visualizer:
    build:
      context: .
      args:
        - arg_debug_mode=True
    command: ./manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - database
      - selenium
      - redis
    environment:
      - GEO_KEY=$GEO_KEY
      - SECRET_KEY=$SECRET_KEY
      - ADMINS=$ADMINS
      - MANAGERS=$MANAGERS
      - EMAIL_URL=$EMAIL_URL
      - SENTRY_DSN=$SENTRY_DSN
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
  database:
    image: postgis/postgis:12-master
    volumes:
      - postgis_orm:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=data_manager
    ports:
      - "${DB_PORT}:${DB_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    build:
      context: nginx
    ports:
      - 5000:80
    depends_on:
      - visualizer
  selenium:
    image: selenium/standalone-chrome
    ports:
      - 4444

  redis:
    image: redis:6
    ports:
      - 6379:6379

volumes:
  postgis_orm:
